# Countries statistics and energy use statistics

This notebook will document the entire creation of the final dataset
The dataset is sourced from Our World in Data's Energy Data and World Bank's Datasets.

In [1]:
# import needed packages
import pandas as pd
import world_bank_data as wb

## Entities

In [2]:
# read entities dataset
df_entities = pd.read_csv("entities/entities.csv")
df_entities

,Code,Entity,OWID,OWID_Name,OWID_Continent,OWID_WHO_Region,OWID_WB_Region,OWID_UN_Region,WB,WB_ISO2,WB_Name,WB_region,WB_adminregion,WB_incomeLevel,WB_lendingType,WB_capitalCity,WB_longitude,WB_latitude,WEO,WEO_Country
0,ABW,Aruba,ABW,Aruba,North America,NaN,Latin America and Caribbean,Latin America and Caribbean,ABW,AW,Aruba,Latin America & Caribbean,NaN,High income,Not classified,Oranjestad,-70.0167,12.51670,ABW,Aruba
1,AFE,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,AFE,ZH,Africa Eastern and Southern,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,AFG,Afghanistan,Asia,Eastern Mediterranean,South Asia,Central and Southern Asia,AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.52280,AFG,Afghanistan
3,AFW,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,AFW,ZI,Africa Western and Central,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN
4,AGO,Angola,AGO,Angola,Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa,AGO,AO,Angola,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Luanda,13.2420,-8.81155,AGO,Angola
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,Wake Island,NaN,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,NaN,Non-OECD,NaN,Non-OECD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,NaN,Oceania,NaN,Oceania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,NaN,Asia,NaN,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,NaN,CIS,NaN,CIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Our World in Data

In [3]:
# load the dataset
df_owid = pd.read_csv("https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv")
df_owid

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17234,ZWE,Zimbabwe,2016,-37.694,-12.257,NaN,0.0,NaN,0.0,-14.611,...,NaN,0.713,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17235,ZWE,Zimbabwe,2017,8.375,1.697,NaN,NaN,NaN,NaN,-1.564,...,NaN,0.702,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17236,ZWE,Zimbabwe,2018,14.336,3.148,NaN,NaN,NaN,NaN,3.409,...,NaN,0.693,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17237,ZWE,Zimbabwe,2019,-21.529,-5.405,NaN,NaN,NaN,NaN,4.052,...,NaN,0.683,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17238,ZWE,Zimbabwe,2020,24.859,4.897,NaN,NaN,NaN,NaN,NaN,...,NaN,0.673,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

### Transform data

In [4]:
# transform data

# transform year to int data type
# this is so that iso_code + year can be compatible primary keys with the world bank dataset
df_owid["year"] = df_owid["year"].transform(int)
df_owid

# remove country column
# We already have defined the country names in the "entities" table
df_owid.drop(columns="country", inplace=True)
df_owid

,iso_code,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,energy_cons_change_twh,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17234,ZWE,2016,-37.694,-12.257,NaN,0.0,NaN,0.0,-14.611,-7.985,...,NaN,0.713,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17235,ZWE,2017,8.375,1.697,NaN,NaN,NaN,NaN,-1.564,-0.730,...,NaN,0.702,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17236,ZWE,2018,14.336,3.148,NaN,NaN,NaN,NaN,3.409,1.566,...,NaN,0.693,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17237,ZWE,2019,-21.529,-5.405,NaN,NaN,NaN,NaN,4.052,1.925,...,NaN,0.683,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17238,ZWE,2020,24.859,4.897,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.673,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

#### Transform iso_code to Entities Code

In [5]:
# transform iso code to Entities Code

# df_entities Code and OWID
df_entities[["Code", "OWID"]]

#  merge df_owid with df_entities[["Code", "OWID"]]
df_owid = pd.merge(df_entities[["Code", "OWID"]], df_owid, how="right", left_on="Code", right_on="iso_code")
df_owid

# transform iso_code to standard df_entities Code
df_owid["iso_code"] = df_owid["Code"]
df_owid

# remove Code and OWID
# we can ensure that this cannot affect the original OWID dataset, since there is no variable in the dataset name "Code" or "OWID"
df_owid.drop(columns=["Code", "OWID"], inplace=True)
df_owid

,iso_code,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,energy_cons_change_twh,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47177,ZWE,2016,-37.694,-12.257,NaN,0.0,NaN,0.0,-14.611,-7.985,...,NaN,0.713,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
47178,ZWE,2017,8.375,1.697,NaN,NaN,NaN,NaN,-1.564,-0.730,...,NaN,0.702,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
47179,ZWE,2018,14.336,3.148,NaN,NaN,NaN,NaN,3.409,1.566,...,NaN,0.693,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
47180,ZWE,2019,-21.529,-5.405,NaN,NaN,NaN,NaN,4.052,1.925,...,NaN,0.683,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
47181,ZWE,2020,24.859,4.897,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.673,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

### Melt the dataset

In [6]:
# melt dataset and remove nan values

# melt the dataset
df_owid = pd.melt(df_owid, id_vars=["iso_code", "year"], var_name="attr", value_name="owid")
df_owid

# remove nan values
df_owid.dropna(inplace=True)
df_owid

         iso_code  year                    attr     owid
50            AFG  1950    coal_prod_change_pct  180.000
51            AFG  1951    coal_prod_change_pct    7.143
52            AFG  1952    coal_prod_change_pct   13.333
53            AFG  1953    coal_prod_change_pct   -5.882
54            AFG  1954    coal_prod_change_pct   -6.250
...           ...   ...                     ...      ...
5894875  OWID_WRL  2016  wind_energy_per_capita  324.182
5894876  OWID_WRL  2017  wind_energy_per_capita  377.678
5894877  OWID_WRL  2018  wind_energy_per_capita  413.472
5894878  OWID_WRL  2019  wind_energy_per_capita  455.268
5894879  OWID_WRL  2020  wind_energy_per_capita  503.633

[682397 rows x 4 columns]

## World Bank

### Sample Code

In [7]:
# get series
# the output is a Series with MultiLevel Index 
# id or value is id, meaning that the Country value will be the ISO code instead of name, and Series value will be Indicator Code instead of Indicator name
df_sample: pd.Series = wb.get_series(indicator="AG.LND.TOTL.K2", id_or_value="id")
df_sample

Country  Series          Year
AFE      AG.LND.TOTL.K2  1960             NaN
                         1961    1.477796e+07
                         1962    1.477796e+07
                         1963    1.477796e+07
                         1964    1.477796e+07
                                     ...
ZWE      AG.LND.TOTL.K2  2017    3.868500e+05
                         2018    3.868500e+05
                         2019    3.868500e+05
                         2020    3.868500e+05
                         2021    3.868500e+05
Name: AG.LND.TOTL.K2, Length: 16492, dtype: float64

In [8]:
# transform the series to dataframe with name "Value". The name will be the value column name when transformed to normal table
df_sample = df_sample.to_frame("Value")
df_sample

                                    Value
Country Series         Year
AFE     AG.LND.TOTL.K2 1960           NaN
                       1961  1.477796e+07
                       1962  1.477796e+07
                       1963  1.477796e+07
                       1964  1.477796e+07
...                                   ...
ZWE     AG.LND.TOTL.K2 2017  3.868500e+05
                       2018  3.868500e+05
                       2019  3.868500e+05
                       2020  3.868500e+05
                       2021  3.868500e+05

[16492 rows x 1 columns]

In [9]:
# reset index in order to change the MultiLevel Index column format to a normal column format
df_sample.reset_index(inplace=True)
df_sample

      Country          Series  Year         Value
0         AFE  AG.LND.TOTL.K2  1960           NaN
1         AFE  AG.LND.TOTL.K2  1961  1.477796e+07
2         AFE  AG.LND.TOTL.K2  1962  1.477796e+07
3         AFE  AG.LND.TOTL.K2  1963  1.477796e+07
4         AFE  AG.LND.TOTL.K2  1964  1.477796e+07
...       ...             ...   ...           ...
16487     ZWE  AG.LND.TOTL.K2  2017  3.868500e+05
16488     ZWE  AG.LND.TOTL.K2  2018  3.868500e+05
16489     ZWE  AG.LND.TOTL.K2  2019  3.868500e+05
16490     ZWE  AG.LND.TOTL.K2  2020  3.868500e+05
16491     ZWE  AG.LND.TOTL.K2  2021  3.868500e+05

[16492 rows x 4 columns]

In [10]:
# end sample code
del df_sample

### Collect data

In [11]:
# set a dictionary of indicator codes
# each value of the indicator code is the name of the variable in our final dataset
IndicatorCodes = {
    "AG.LND.TOTL.K2": "area",
    "SP.POP.TOTL": "population",
    "NY.GDP.MKTP.CD": "gdp",
    "NY.GDP.MKTP.PP.CD": "gdp_ppp",
    "NY.GDP.PCAP.CD": "gdp_per_captia",
    "NY.GDP.PCAP.PP.CD": "gdp_ppp_per_capita",
}

# get all indicator codes datasets
list_df = []

for indicator_code in IndicatorCodes:
    # get series
    df: pd.Series = wb.get_series(indicator=indicator_code, id_or_value="id")
    # trasnform to dataframe with name Value
    df = df.to_frame("Value")
    # reset index to transform into a normal
    df.reset_index(inplace=True)
    # add to df list
    list_df.append(df)

df_wb = pd.concat(list_df)
df_wb

# then, delete unwanted values
del list_df, df, indicator_code

### Transform data

In [12]:
# transform data

# rename "Series" value 
# in order to match variable value with OWID data
df_wb["Series"] = df_wb["Series"].transform(lambda x: IndicatorCodes[x])
df_wb

# remove nan values
df_wb.dropna(inplace=True)
df_wb

# rename column, prepare to join with df_owid
df_wb.rename(columns={
    "Country": "iso_code",
    "Year": "year",
    "Series": "attr",
    "Value": "wb"
}, inplace=True)
df_wb

# transform year to int data type
# this is so that iso_code + year can be compatible primary keys with the owid dataset
df_wb["year"] = df_wb["year"].transform(int)
df_wb

      iso_code                attr  year            wb
1          AFE                area  1961  1.477796e+07
2          AFE                area  1962  1.477796e+07
3          AFE                area  1963  1.477796e+07
4          AFE                area  1964  1.477796e+07
5          AFE                area  1965  1.477796e+07
...        ...                 ...   ...           ...
16486      ZWE  gdp_ppp_per_capita  2016  2.806469e+03
16487      ZWE  gdp_ppp_per_capita  2017  3.795642e+03
16488      ZWE  gdp_ppp_per_capita  2018  4.017222e+03
16489      ZWE  gdp_ppp_per_capita  2019  3.783548e+03
16490      ZWE  gdp_ppp_per_capita  2020  3.537351e+03

[72259 rows x 4 columns]

### Transform iso_code to Entity Code

In [13]:
# transform iso code to entity code

# df_entities Code and OWID
df_entities[["Code", "WB"]]

#  merge df_owid with df_entities[["Code", "OWID"]]
df_wb = pd.merge(df_entities[["Code", "WB"]], df_wb, how="right", left_on="Code", right_on="iso_code")
df_wb

# transform iso_code to standard df_entities Code
df_wb["iso_code"] = df_wb["Code"]
df_wb

# remove Code and WB
df_wb.drop(columns=["Code", "WB"], inplace=True)
df_wb

# remove nan values
df_wb.dropna(inplace=True)
df_wb

      iso_code                attr  year            wb
0          AFE                area  1961  1.477796e+07
1          AFE                area  1962  1.477796e+07
2          AFE                area  1963  1.477796e+07
3          AFE                area  1964  1.477796e+07
4          AFE                area  1965  1.477796e+07
...        ...                 ...   ...           ...
72254      ZWE  gdp_ppp_per_capita  2016  2.806469e+03
72255      ZWE  gdp_ppp_per_capita  2017  3.795642e+03
72256      ZWE  gdp_ppp_per_capita  2018  4.017222e+03
72257      ZWE  gdp_ppp_per_capita  2019  3.783548e+03
72258      ZWE  gdp_ppp_per_capita  2020  3.537351e+03

[71641 rows x 4 columns]

### Merge OWID and WB data

In [14]:
# merge owid and wb data

# merge df_owid with df_wb
df = pd.merge(df_owid, df_wb, how="outer", on=["iso_code", "year", "attr"])
df

# merge two values from two different datasets
# we prioritize wb values
df["value"] = df["wb"].fillna(df["owid"])
df

# remove owid and wb, only keep value
df = df[["iso_code", "year", "attr", "value"]]
df

       iso_code  year                  attr        value
0           AFG  1950  coal_prod_change_pct   180.000000
1           AFG  1951  coal_prod_change_pct     7.143000
2           AFG  1952  coal_prod_change_pct    13.333000
3           AFG  1953  coal_prod_change_pct    -5.882000
4           AFG  1954  coal_prod_change_pct    -6.250000
...         ...   ...                   ...          ...
736790      ZWE  2016    gdp_ppp_per_capita  2806.469032
736791      ZWE  2017    gdp_ppp_per_capita  3795.642431
736792      ZWE  2018    gdp_ppp_per_capita  4017.221716
736793      ZWE  2019    gdp_ppp_per_capita  3783.547898
736794      ZWE  2020    gdp_ppp_per_capita  3537.351394

[736795 rows x 4 columns]

## Entities Groups

In [15]:
# variables needed
# variables name and matching column in Entities dataset
vars = {
    "iso_code": "Code",
    "country": "Entity",
    "group_OWID_Continent": "OWID_Continent",
    "group_UN_Region": "OWID_UN_Region",
    "group_WHO_Region": "OWID_WHO_Region",
    "group_WB_region": "WB_region",
    "group_WB_adminregion": "WB_adminregion",
    "group_WB_incomeLevel": "WB_incomeLevel",
    "group_WB_lendingType": "WB_lendingType",
    "group_WB_longitude": "WB_longitude",
    "group_WB_latitude": "WB_latitude"
}

# variables of group type
# each of these variable will have a twin variable with the US's value always equals United States
# this is so that in the visualisation, the US can be highlighted
vars_group = [
    "group_OWID_Continent",
    "group_UN_Region",
    "group_WHO_Region",
    "group_WB_region",
    "group_WB_adminregion",
    "group_WB_incomeLevel",
    "group_WB_lendingType"
]

In [16]:

# create df_groups

df_groups = pd.DataFrame()

for k in vars:

    df_groups[k] = df_entities[vars[k]]

df_groups

,iso_code,country,group_OWID_Continent,group_UN_Region,group_WHO_Region,group_WB_region,group_WB_adminregion,group_WB_incomeLevel,group_WB_lendingType,group_WB_longitude,group_WB_latitude
0,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,12.51670
1,AFE,Africa Eastern and Southern,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN
2,AFG,Afghanistan,Asia,Central and Southern Asia,Eastern Mediterranean,South Asia,South Asia,Low income,IDA,69.1761,34.52280
3,AFW,Africa Western and Central,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN
4,AGO,Angola,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,13.2420,-8.81155
...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,NaN,Non-OECD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,NaN,Oceania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,NaN,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,NaN,CIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:

# add twin attributes that prioritize US

for k in vars_group:

    df_groups[k + "_exclude_US"] = df_groups[k]

    df_groups.loc[df_groups["country"] == "United States", k + "_exclude_US"] = "United States"

df_groups

,iso_code,country,group_OWID_Continent,group_UN_Region,group_WHO_Region,group_WB_region,group_WB_adminregion,group_WB_incomeLevel,group_WB_lendingType,group_WB_longitude,group_WB_latitude,group_OWID_Continent_exclude_US,group_UN_Region_exclude_US,group_WHO_Region_exclude_US,group_WB_region_exclude_US,group_WB_adminregion_exclude_US,group_WB_incomeLevel_exclude_US,group_WB_lendingType_exclude_US
0,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,12.51670,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified
1,AFE,Africa Eastern and Southern,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates
2,AFG,Afghanistan,Asia,Central and Southern Asia,Eastern Mediterranean,South Asia,South Asia,Low income,IDA,69.1761,34.52280,Asia,Central and Southern Asia,Eastern Mediterranean,South Asia,South Asia,Low income,IDA
3,AFW,Africa Western and Central,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates
4,AGO,Angola,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,13.2420,-8.81155,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,NaN,Non-OECD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,NaN,Oceania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,NaN,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,NaN,CIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:

# add a variable that equals United States if and only if the Entity is United States

df_groups["group_is_USA"] = df_groups["country"].copy(deep=True).transform(lambda x: x if x == "United States" else "Other Entities")

df_groups

,iso_code,country,group_OWID_Continent,group_UN_Region,group_WHO_Region,group_WB_region,group_WB_adminregion,group_WB_incomeLevel,group_WB_lendingType,group_WB_longitude,group_WB_latitude,group_OWID_Continent_exclude_US,group_UN_Region_exclude_US,group_WHO_Region_exclude_US,group_WB_region_exclude_US,group_WB_adminregion_exclude_US,group_WB_incomeLevel_exclude_US,group_WB_lendingType_exclude_US,group_is_USA
0,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,12.51670,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,Other Entities
1,AFE,Africa Eastern and Southern,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,Other Entities
2,AFG,Afghanistan,Asia,Central and Southern Asia,Eastern Mediterranean,South Asia,South Asia,Low income,IDA,69.1761,34.52280,Asia,Central and Southern Asia,Eastern Mediterranean,South Asia,South Asia,Low income,IDA,Other Entities
3,AFW,Africa Western and Central,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN,NaN,NaN,Aggregates,NaN,Aggregates,Aggregates,Other Entities
4,AGO,Angola,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,13.2420,-8.81155,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Other Entities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Entities
392,NaN,Non-OECD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Entities
393,NaN,Oceania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Entities
394,NaN,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Entities
395,NaN,CIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Entities

In [19]:
# remove not needed variables in this script
del vars, vars_group, k, IndicatorCodes

## Final

In [20]:
# pivot dataset
df = pd.pivot(df, index=["iso_code", "year"], columns="attr", values="value")
df

# reset index
# reset index to make iso_code and year become normal attributes again
df.reset_index(inplace=True)
df

# merge values dataset with groups dataset
df = pd.merge(df_groups, df, on="iso_code", how="right")
df

,iso_code,country,group_OWID_Continent,group_UN_Region,group_WHO_Region,group_WB_region,group_WB_adminregion,group_WB_incomeLevel,group_WB_lendingType,group_WB_longitude,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,North America,Latin America and Caribbean,NaN,Latin America & Caribbean,NaN,High income,Not classified,-70.0167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22306,ZWE,Zimbabwe,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,31.0672,...,0.137,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22307,ZWE,Zimbabwe,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,31.0672,...,0.110,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22308,ZWE,Zimbabwe,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,31.0672,...,0.088,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22309,ZWE,Zimbabwe,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,31.0672,...,0.088,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22310,ZWE,Zimbabwe,Africa,Sub-Saharan Africa,Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,31.0672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# write dataset to json
df.to_json("data.json", orient="records")

In [22]:
# write dataset to csv
df.to_csv("data.csv", index=False)